; Test stdlib compilation
(import "stdlib.lisp")

(print-int (abs (- 5)))
(print-int (min 3 8))
(print-int (max 3 8))
(print-int (inc 5))
(print-int (dec 5))
(print-int (if (zero? 0) 1 0))
(print-int (if (pos? 5) 1 0))
(print-int (if (neg? (- 3)) 1 0))
(print-int (if (even? 4) 1 0))
(print-int (if (odd? 3) 1 0))
(print-int (if (my-and #t #t) 1 0))
(print-int (if (my-or #t #f) 1 0))
(print-int (if (not #f) 1 0))
(print-nl)
(print-int (within? 5 1 10))
(print-int (within? 15 1 10))